version: '3'

services:
  postgres:
    image: postgres:12
    command: postgres -c max_prepared_transactions=100
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./compose-init.sql:/docker-entrypoint-initdb.d/compose-init.sql
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - 5432:5432

      
volumes:
  postgres-data: